[TOC]



# 异常处理(2022.2.11)

## 1.什么是异常

异常就是程序出现错误，程序一旦出现错误，就会终止程序。

1.1异常处理的三个特征



## 2.为什么要处理异常

为了程序更好的运行，即使程序出现错误，也不能终止程序。而是捕捉错误，并记录错误。

![](https://s2.loli.net/2022/02/11/Kt5bchfnvpNexHE.jpg)

### 语法错误

SyntaxError

要在程序运行前修改

### 逻辑错误

```python
# TypeError：数字类型无法与字符串类型相加
1+’2’

# ValueError：当字符串包含有非数字的值时，无法转成int类型
num=input(">>: ") #输入hello
int(num)

# NameError：引用了一个不存在的名字x
x

# IndexError：索引超出列表的限制
l=['egon','aa']
l[3]

# KeyError：引用了一个不存在的key
dic={'name':'egon'}
dic['age']

# AttributeError：引用的属性不存在
class Foo:
    pass
Foo.x

# ZeroDivisionError：除数不能为0
1/0
```

### 异常处理

#### 用法一

```python
try:
    被检测的代码块
except 异常类型：
    检测到异常，就执行这个位置的逻辑
```

#### 用法二

如果我们想分别用不同的逻辑处理，需要用到多分支的except（类似于多分支的elif，从上到下依次匹配，匹配成功一次便不再匹配其他）

```python
try:
    被检测的代码块
except NameError:
    触发NameError时对应的处理逻辑
except IndexError:
    触发IndexError时对应的处理逻辑
except Exception:
    其他类型的异常统一用此处的逻辑处理
```

#### 用法三

如果except后的子代码一样可以将错误类型写在一起。

```python
try:
    被检测的代码块
except (NameError,IndexError,TypeError):
    触发NameError或IndexError或TypeError时对应的处理逻辑
```

#### 用法四

如果我们想捕获所有异常并用一种逻辑处理，Python提供了一个万能异常类型**Exception**

```python
try:
    被检测的代码块
except NameError:
    触发NameError时对应的处理逻辑
except IndexError:
    触发IndexError时对应的处理逻辑
except Exception:
    其他类型的异常统一用此处的逻辑处理
```

#### else

在多分支except之后还可以跟一个else（else必须跟在except之后，不能和try单独使用），**只有在被检测的代码块没有触发任何异常的情况下才会执行else的子代码块**

```python
try:
    被检测的代码块
except 异常类型1:
    pass
except 异常类型2:
    pass
......
else:
    没有异常发生时执行的代码块
```

#### finally

此外try还可以与finally连用，从语法上讲finally必须放到else之后，但可以使用try-except-finally的形式，也可以直接使用try-finally的形式。无论被检测的代码块是否触发异常，都会执行finally的子代码块，因此通常在finally的子代码块做一些回收资源的操作，比如关闭打开的文件、关闭数据库连接等

```python
f=None
try:
    f=open(‘db.txt’,'r',encoding='utf-8')
    s=f.read().strip()
    int(s)  # 若字符串s中包含非数字时则会触发异常ValueError
    # f.close() # 若上面的代码触发异常，则根本不可能执行到此处的代码，应该将关闭文件的操作放到finally中
finally:
    if f: # 文件存在则f的值不为None
        f.close()
```
